name = "minesweeper-server"
main = "server/src/index.js"
compatibility_date = "2026-07-01"

[[durable_objects.bindings]]
name = "GAME"
class_name = "GameRoom"

[[durable_objects.bindings]]
name = "LEADERBOARD"
class_name = "Leaderboard"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Leaderboard"]
